# Generated by Django 4.0.3 on 2022-07-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_health_travelhistory_alter_health_choise3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='choise3',
            field=models.CharField(choices=[(0, 'None'), (1, 'Headache'), (2, 'Cough'), (3, 'High Fever')], max_length=50, null=True),
        ),
    ]
