# Generated by Django 4.0.3 on 2022-07-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_health_choise3'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='health',
            table=None,
        ),
    ]
