# Generated by Django 3.2.10 on 2022-07-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_health_img_alter_health_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='health',
            table=None,
        ),
    ]
