# Generated by Django 3.2.10 on 2022-07-22 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_health_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
