# Generated by Django 3.2.10 on 2022-07-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220722_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='img',
        ),
    ]
