# Generated by Django 3.2.10 on 2022-07-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_health_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='img',
            field=models.ImageField(null=True, upload_to='student_img'),
        ),
    ]
