# Generated by Django 3.2.10 on 2022-08-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20220810_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
