# Generated by Django 3.2.10 on 2022-08-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_health_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
