# Generated by Django 4.0.3 on 2022-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phonenumber', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('temperature', models.CharField(max_length=20, null=True)),
                ('choise1', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], null=True)),
                ('choise2', models.BooleanField(choices=[(1, '1st Dose'), (0, 'Fully Vaccinated')], null=True)),
                ('choise3', models.CharField(choices=[(0, 'NONE'), (1, 'Headache'), (2, 'Coughing'), (3, 'HighFever')], default='NONE', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='HealthForms',
        ),
    ]
