# Generated by Django 4.0.3 on 2022-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_health_delete_healthforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='travelhistory',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='choise3',
            field=models.BooleanField(choices=[(0, 'NONE'), (1, 'Headache'), (2, 'Coughing'), (3, 'HighFever')], null=True),
        ),
        migrations.AlterModelTable(
            name='health',
            table='Health',
        ),
    ]
