# Generated by Django 4.0.3 on 2022-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_health_choise3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='choise3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
