# Generated by Django 4.0.3 on 2022-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_health_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterModelTable(
            name='health',
            table='HealthForms',
        ),
    ]
